stages:
  - test
  - e2e

default:
  tags:
    - cstack
    - no_root

test-frontend:
  stage: test
  image: node:20-alpine
  before_script:
    - cd ./todo-frontend && npm install 
  script:
    - npm run test
  cache:
    key:
      files:
        - todo-frontend/package-lock.json
    paths:
      - todo-frontend/node_modules

test-backend-js:
  stage: test
  image: node:20-alpine
  before_script:
    - cd ./todo-backend/todo-app-js
    - npm install 
  script:
    - npm run test
  cache:
    key:
      files:
        - todo-backend/todo-app-js/package-lock.json
    paths:
      - todo-backend/todo-app-js/node_modules

test-backend-python:
  stage: test
  image: python:3-slim
  before_script:
    - cd ./todo-backend/todo-app-python
    - pip install -r requirements.txt
  script:
    - /tmp/.local/bin/pytest --disable-warnings

test-backend-java:
  stage: test
  image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
  before_script:
    - cd ./todo-backend/todo-app-java
  script:
    - ./gradlew test

test-e2e-js:
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.47.2-jammy
  needs:
    - test-frontend
    - test-backend-js
  before_script:
    - cd ./todo-frontend && npm install && cd ../todo-backend/todo-app-js && npm install && cd ../../e2e/js && npm install
  script:
    - npm run test
  cache:
    - key:
        files:
          - todo-frontend/package-lock.json
      paths:
        - todo-frontend/node_modules
    - key:
        files:
          - todo-backend/todo-app-js/package-lock.json
      paths:
        - todo-backend/todo-app-js/node_modules
    - key:
        files:
          - e2e/js/package-lock.json
      paths:
        - e2e/js/node_modules
    

# - cd ./todo-frontend && cd ../todo-backend/todo-app-js && npm install && cd ../../e2e/js && npm install