stages:
  - test

test-frontend:
  stage: test
  image: node:20-alpine
  before_script:
    - cd ./todo-frontend && npm install 
  script:
    - npm run test

test-backend-js:
  stage: test
  image: node:20-alpine
  before_script:
    - cd ./todo-backend/todo-app-js
    - npm install 
  script:
    - npm run test

test-backend-python:
  stage: test
  image: python:3-slim
  variables:
    PATH: "/tmp/.local/bin:$PATH"
  before_script:
    - cd ./todo-backend/todo-app-python
    - pip install -r requirements.txt
  script:
    - pytest --disable-warnings

test-backend-java:
  stage: test
  image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
  before_script:
    - cd ./todo-backend/todo-app-java
  script:
    - ./gradlew test



# test-e2e-js:
#   stage: test
#   before_script:
#     - cd ./todo-frontend && cd ../todo-backend/todo-app-js && npm install && cd ../../e2e/js && npm install
#   script:
#     - npm run test

# - cd ./todo-frontend && cd ../todo-backend/todo-app-js && npm install && cd ../../e2e/js && npm install